# Generated by Django 5.1 on 2024-11-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_profile_role_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('User', 'user')], default='user', max_length=10),
        ),
    ]
