# Generated by Django 5.1 on 2024-11-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('Users', 'users')], default='user', max_length=10),
        ),
    ]
