# Generated by Django 5.1 on 2024-12-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_rename_credit_profile_balance_alter_driver_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.driver'),
        ),
    ]
