# Generated by Django 5.1 on 2024-12-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_receipt_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='driver',
        ),
        migrations.AddField(
            model_name='receipt',
            name='driver_firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='driver_lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
