# Generated by Django 5.1 on 2024-12-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_profile_license_number_receipt_license_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='driver_firstname',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='driver_lastname',
        ),
    ]
